name: Lint and Build

on:
  push:
    branches: ['production', 'staging', 'development']
  pull_request:
    branches: ['production', 'staging', 'development']

jobs:
  lint:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Use Node.js 22.x
        uses: actions/setup-node@v6
        with:
          node-version: '22.x'
          cache: 'pnpm'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@jacliner'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: pnpm install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check formatting with Prettier
        run: pnpm format:check

      - name: Run ESLint
        run: pnpm lint

  build:
    needs: lint
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read

    strategy:
      matrix:
        node-version: [22.x, 24.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@jacliner'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: pnpm install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build project
        run: pnpm run build
